### PR TITLE
Python version bump.

### PR DESCRIPTION
**Pull request by DinoBektesevic**
Updating Python to 3.10.
This is a fixed PR of: https://github.com/dirac-institute/trailblazer/pull/42

### CODE REVIEW

**Comment by DinoBektesevic** [comment]
[Bump Python version to 3.10](https://trello.com/c/KkWFSQHq/35-bump-python-version-to-310)

**Comment by DinoBektesevic** [comment]
[Bump Python version to 3.10](https://trello.com/c/KkWFSQHq/35-bump-python-version-to-310)

**Comment by DinoBektesevic** [comment]
[Bump Python version to 3.10](https://trello.com/c/KkWFSQHq/35-bump-python-version-to-310)

**Review by mrawls — APPROVED** [review]
Looks good, excellent catch on astro_metadata_translator install in particular. I am cautiously optimistic your trimmed down requirements.txt list will be sufficient too.

**Pull request merged**
