### PR TITLE
Generalize query function

### PR DESCRIPTION
**Pull request by Jasminewatt2100**
Fall 2021 quarter progress: wcs information added to the query result table.

### CODE REVIEW

**Comment by mrawls** [comment]
[Extend query webpage to handle more fields](https://trello.com/c/bKtOKXlJ/29-extend-query-webpage-to-handle-more-fields)

**Comment by mrawls** [comment]
[Actually review and merge PR 40](https://trello.com/c/CuEa7nLt/31-actually-review-and-merge-pr-40)

**Comment by mrawls** [comment]
I didn't realize our new Trello board would post comments here 😄 well, this is officially on my radar again!

**Comment by Jasminewatt2100** [comment]
No worries! Hope the progress is going well.

**Review by mrawls — APPROVED** [review]
Thank you for working on this last quarter, Jasmine! I think this adds a nice bit of functionality to the query page. It looks good and we should get it merged to main. Happy to let you do that, or I can do it for you, whatever you prefer.

**Comment by Jasminewatt2100** [comment]
I can find some time to merge it on this weekend-- just remind me the steps of merging would be great.

**Comment by mrawls** [comment]
Two options.  One is clicking the big green button right here that says "Merge pull request"! The other option uses the command line and is what I normally do. But the end result should be the same.
```
cd trailblazer
git checkout main
--> (if you get a complaint about changes that haven't been committed and you're sure they're not important):
--> git reset --hard origin/generalize-query-function (force your computer's version to match GitHub's version)
--> git checkout main (for reals this time)
git pull (ensure you have all the latest stuff from the main branch)
git status (should say, "on branch main, everything is up to date," effectively)
git merge --no-ff generalize-query-function
git push
```

**Comment by Jasminewatt2100** [comment]
I used the codes provided to merge, and seemly it was successful. Feel free to let me know if there is any issue.

**Pull request merged**
